<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Authentication\Models\User;
use App\Domains\Municipality\Enums\CouncilMemberPosition;
use App\Domains\Municipality\Enums\CouncilMemberStatus;
use App\Domains\Municipality\Models\CouncilMember;
use Illuminate\Database\Seeder;

final class CouncilMemberSeeder extends Seeder
{
    public function run(): void
    {
        $userId = User::query()->value('id');
        $termStart = '2026-04-25';

        $members = [
            [
                'full_name' => 'رزق شاكر سلامه اطميزه',
                'slug' => 'rizq-shaker-salama-atmeizeh',
                'position' => CouncilMemberPosition::Mayor->value,
                'qualification' => null,
                'profession' => 'رئيس بلدية إذنا',
                'bio' => 'رئيس بلدية إذنا، ويقود المجلس البلدي في متابعة شؤون البلدية وتعزيز الخدمات والمشاريع المحلية وخدمة المجتمع.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 1,
                'is_public' => true,
                'is_featured' => true,
            ],
            [
                'full_name' => 'تامر زاهر موسى أبو جحيشة',
                'slug' => 'tamer-zaher-mousa-abu-juhaysha',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => 'رجل أعمال، ولديه خبرة سابقة في المجلس البلدي',
                'bio' => 'عضو في المجلس البلدي، وهو رجل أعمال لديه خبرة سابقة في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 2,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'يوسف عبد ربه يوسف البطران',
                'slug' => 'yousef-abd-rabuh-yousef-al-batran',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => 'تمريض',
                'profession' => 'ممرض',
                'bio' => 'عضو في المجلس البلدي ويعمل ممرضًا.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 3,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'طارق أحمد محمد فرج الله',
                'slug' => 'tariq-ahmad-mohammad-farajallah',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => 'قانون',
                'profession' => 'محامٍ',
                'bio' => 'عضو في المجلس البلدي ويعمل محاميًا.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 4,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'يزن حلمي محمد عواد',
                'slug' => 'yazan-hilmi-mohammad-awad',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => null,
                'bio' => 'عضو في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 5,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'ألين نادر إبراهيم صوايفه',
                'slug' => 'aleen-nader-ibrahim-swayfeh',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => null,
                'bio' => 'عضو في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 6,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'محمد خالد أحمد طميزه',
                'slug' => 'mohammad-khaled-ahmad-tamizeh',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => 'تعليم / رياضيات',
                'profession' => 'مربٍ ومعلم رياضيات، ونائب مدير مدرسة',
                'bio' => 'عضو في المجلس البلدي، وهو مربٍ ومعلم رياضيات ونائب مدير مدرسة.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 7,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'أحمد ديب محمد نوفل',
                'slug' => 'ahmad-deeb-mohammad-nofal',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => 'الهندسة',
                'profession' => 'مهندس',
                'bio' => 'عضو في المجلس البلدي ويعمل مهندسًا.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 8,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'إبراهيم علي محمد عوض',
                'slug' => 'ibrahim-ali-mohammad-awad',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => null,
                'bio' => 'عضو في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 9,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'شوقي إبراهيم محمود جياوي',
                'slug' => 'shawqi-ibrahim-mahmoud-jiawi',
                'position' => CouncilMemberPosition::DeputyMayor->value,
                'qualification' => 'الهندسة',
                'profession' => 'مهندس',
                'bio' => 'نائب رئيس البلدية وعضو في المجلس البلدي، ويعمل مهندسًا.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 10,
                'is_public' => true,
                'is_featured' => true,
            ],
            [
                'full_name' => 'مها يوسف عبد المجيد طمايزه',
                'slug' => 'maha-yousef-abdelmajid-tamayzeh',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => null,
                'bio' => 'عضو في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 11,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'سعاد محمد بدوي طميزه',
                'slug' => 'souad-mohammad-badawi-tamizeh',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => 'كاتبة وروائية',
                'bio' => 'عضو في المجلس البلدي، وهي كاتبة وروائية.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 12,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'full_name' => 'رانيه فضل عبد الله حتاوي',
                'slug' => 'rania-fadl-abdullah-hattawi',
                'position' => CouncilMemberPosition::CouncilMember->value,
                'qualification' => null,
                'profession' => null,
                'bio' => 'عضو في المجلس البلدي.',
                'photo_path' => null,
                'phone' => null,
                'mobile' => null,
                'email' => null,
                'address' => null,
                'facebook' => null,
                'twitter' => null,
                'linkedin' => null,
                'term_start' => $termStart,
                'term_end' => null,
                'years_of_experience' => null,
                'committee' => null,
                'status' => CouncilMemberStatus::Active->value,
                'display_order' => 13,
                'is_public' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($members as $member) {
            CouncilMember::updateOrCreate(
                ['slug' => $member['slug']],
                [
                    ...$member,
                    'national_number' => null,
                    'created_by' => $userId,
                    'updated_by' => $userId,
                ],
            );
        }
    }
}
