<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Authentication\Models\User;
use App\Domains\Municipality\Models\CouncilMember;
use Illuminate\Database\Seeder;

final class CouncilMemberSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::first()?->id;

        $members = [
            [
                'full_name' => 'أحمد محمد عودة',
                'position' => 'رئيس المجلس البلدي',
                'qualification' => 'بكالوريوس هندسة مدنية',
                'profession' => 'مهندس مدني',
                'bio' => 'رئيس المجلس البلدي منذ عام 2020. عمل في عدة مشاريع تنموية مهمة في بلدية إذنا.',
                'phone' => '022-123456',
                'mobile' => '0599123456',
                'email' => 'ahmed.ouda@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 15,
                'committee' => 'اللجنة المالية والإدارية',
                'status' => 'active',
                'display_order' => 1,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'محمد سالم حسونة',
                'position' => 'نائب رئيس المجلس',
                'qualification' => 'بكالوريوس إدارة أعمال',
                'profession' => 'رائد أعمال',
                'bio' => 'نائب رئيس المجلس ومسؤول عن لجنة المشاريع التنموية.',
                'phone' => '022-234567',
                'mobile' => '0599234567',
                'email' => 'mohammad.hassouna@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 12,
                'committee' => 'لجنة المشاريع التنموية',
                'status' => 'active',
                'display_order' => 2,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'خالد يوسف عودة',
                'position' => 'عضو',
                'qualification' => 'بكالوريوس حقوق',
                'profession' => 'محامي',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة الشؤون القانونية.',
                'phone' => '022-345678',
                'mobile' => '0599345678',
                'email' => 'khalid.ouda@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 10,
                'committee' => 'لجنة الشؤون القانونية',
                'status' => 'active',
                'display_order' => 3,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'فاطمة أحمد حسونة',
                'position' => 'عضو',
                'qualification' => 'ماجستير تربية',
                'profession' => 'مدرسة',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة الشؤون الاجتماعية والتعليمية.',
                'phone' => '022-456789',
                'mobile' => '0599456789',
                'email' => 'fatima.hassouna@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 8,
                'committee' => 'لجنة الشؤون الاجتماعية',
                'status' => 'active',
                'display_order' => 4,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'عبدالله حسن عودة',
                'position' => 'عضو',
                'qualification' => 'بكالوريوس هندسة كهربائية',
                'profession' => 'مهندس كهرباء',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة البنية التحتية.',
                'phone' => '022-567890',
                'mobile' => '0599567890',
                'email' => 'abdullah.ouda@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 11,
                'committee' => 'لجنة البنية التحتية',
                'status' => 'active',
                'display_order' => 5,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'نور الدين محمد عودة',
                'position' => 'عضو',
                'qualification' => 'بكالوريوس تجارة',
                'profession' => 'محاسب',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة المالية والميزانية.',
                'phone' => '022-678901',
                'mobile' => '0599678901',
                'email' => 'nour.ouda@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 9,
                'committee' => 'لجنة المالية والميزانية',
                'status' => 'active',
                'display_order' => 6,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'سامي جبر عودة',
                'position' => 'عضو',
                'qualification' => 'بكالوريوس هندسة مدنية',
                'profession' => 'مهندس مدني',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة الإشراف على المشاريع.',
                'phone' => '022-789012',
                'mobile' => '0599789012',
                'email' => 'sami.jabr@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 13,
                'committee' => 'لجنة الإشراف على المشاريع',
                'status' => 'active',
                'display_order' => 7,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'full_name' => 'مها عبدالرحمن حسونة',
                'position' => 'عضو',
                'qualification' => 'ماجستير صحة عامة',
                'profession' => 'طبيبة',
                'bio' => 'عضو في المجلس ومسؤول عن لجنة الصحة والبيئة.',
                'phone' => '022-890123',
                'mobile' => '0599890123',
                'email' => 'maha.hassouna@idhna.ps',
                'term_start' => '2020-01-01',
                'years_of_experience' => 7,
                'committee' => 'لجنة الصحة والبيئة',
                'status' => 'active',
                'display_order' => 8,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
        ];

        foreach ($members as $member) {
            CouncilMember::updateOrCreate(
                ['full_name' => $member['full_name']],
                $member
            );
        }
    }
}
