<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Authentication\Models\User;
use App\Domains\Department\Models\Department;
use Illuminate\Database\Seeder;

final class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $userId = User::query()->value('id');
        $officeLocation = 'مبنى بلدية إذنا';
        $workingHours = 'الأحد - الخميس، 8:00 صباحًا - 3:00 مساءً';

        $departments = [
            [
                'name' => 'خدمات الجمهور',
                'slug' => 'khdmat-algmhor',
                'icon' => 'users',
                'short_description' => 'تقديم خدمات البلدية واستقبال طلبات المواطنين ومتابعتها.',
                'description' => 'تتولى دائرة خدمات الجمهور استقبال المواطنين وتعريفهم بالخدمات البلدية وإجراءات الحصول عليها، واستلام الطلبات والاستفسارات وتوجيهها إلى الجهات المختصة ومتابعة إنجازها بما يعزز سهولة الوصول إلى الخدمة.',
                'manager_name' => 'حسن بشير',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'خدمة جمهور سهلة وواضحة وسريعة تستجيب لاحتياجات المواطنين.',
                'mission' => 'تقديم خدمة محترمة ومنظمة، وتسهيل وصول المواطنين إلى المعلومات والمعاملات البلدية.',
                'responsibilities' => "استقبال المواطنين وتسجيل الطلبات والاستفسارات\nتوضيح إجراءات ومتطلبات الخدمات البلدية\nتوجيه المعاملات إلى الدوائر المختصة\nمتابعة حالة الطلبات وإبلاغ المواطنين بالمستجدات\nرصد الملاحظات والمقترحات وتحويلها إلى الجهات المعنية",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 1,
                'is_public' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'الإدارة',
                'slug' => 'aladar',
                'icon' => 'building-2',
                'short_description' => 'تنسيق العمل الإداري العام ومتابعة شؤون البلدية المؤسسية.',
                'description' => 'تدعم دائرة الإدارة إدارة البلدية في تنسيق أعمال الدوائر ومتابعة تنفيذ التوجيهات والقرارات وتنظيم المراسلات والمعاملات الرسمية، بما يضمن وضوح المسؤوليات واستمرارية العمل المؤسسي.',
                'manager_name' => 'موفق طميزة',
                'manager_position' => 'مدير البلدية',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'إدارة بلدية منسقة وفعالة تضع جودة الخدمة في مقدمة أولوياتها.',
                'mission' => 'تنظيم العمل الإداري ومتابعة أداء الدوائر بما يدعم اتخاذ القرار وتحسين الخدمات.',
                'responsibilities' => "تنسيق العمل بين دوائر البلدية\nمتابعة تنفيذ القرارات والتوجيهات الإدارية\nتنظيم المراسلات والمعاملات الرسمية\nمتابعة سير العمل ورفع الملاحظات للإدارة\nدعم إعداد الخطط والبرامج الإدارية",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 2,
                'is_public' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'المالية',
                'slug' => 'almalyh',
                'icon' => 'wallet',
                'short_description' => 'إدارة الموارد المالية والموازنة والتحصيل والمصروفات البلدية.',
                'description' => 'تتولى دائرة المالية تنظيم الموارد المالية للبلدية ومتابعة الإيرادات والمصروفات وإعداد البيانات والتقارير المالية، بما يدعم الاستخدام المنضبط للموارد وتحسين كفاءة التحصيل والإنفاق.',
                'manager_name' => 'خليل طميزة',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'إدارة مالية شفافة ومستدامة تدعم جودة العمل البلدي.',
                'mission' => 'تنظيم الإيرادات والمصروفات وإعداد البيانات المالية بدقة ومسؤولية.',
                'responsibilities' => "متابعة الإيرادات والتحصيلات البلدية\nتنظيم المصروفات والالتزامات المالية\nالمساهمة في إعداد الموازنة ومتابعة تنفيذها\nإعداد السجلات والتقارير المالية\nالتنسيق المالي مع الدوائر والجهات ذات العلاقة",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 3,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'الهندسة',
                'slug' => 'alhnds',
                'icon' => 'hard-hat',
                'short_description' => 'متابعة المشاريع الهندسية والبنية التحتية والاحتياجات الفنية للبلدية.',
                'description' => 'تتولى دائرة الهندسة متابعة الأعمال والمشاريع الهندسية التابعة للبلدية، ودعم التخطيط الفني للمرافق والبنية التحتية، ومراجعة الاحتياجات الفنية بما يساهم في تنفيذ الأعمال وفق المتطلبات المعتمدة.',
                'manager_name' => 'بيسان جمال طميزة',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'بنية تحتية بلدية أفضل ومشاريع هندسية تلبي احتياجات المجتمع المحلي.',
                'mission' => 'تقديم المتابعة الفنية للمشاريع والأعمال الهندسية وتعزيز جودة التنفيذ.',
                'responsibilities' => "متابعة المشاريع والأعمال الهندسية\nالإشراف على احتياجات البنية التحتية الفنية\nمتابعة المخططات والأعمال الإنشائية ذات العلاقة\nالمساهمة في تنظيم ومتابعة الطرق والمرافق\nإعداد ومتابعة الاحتياجات الفنية للمشاريع",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 4,
                'is_public' => true,
                'is_featured' => true,
            ],
            [
                'name' => 'المياه',
                'slug' => 'almyah',
                'icon' => 'droplet',
                'short_description' => 'متابعة خدمات المياه والتزويد والصيانة والشكاوى المتعلقة بالمياه.',
                'description' => 'تتابع دائرة المياه شؤون تزويد المواطنين بالمياه، وترصد الملاحظات والشكاوى المرتبطة بالخدمة، وتنسق أعمال المتابعة والصيانة اللازمة لشبكة المياه والمرافق المرتبطة بها.',
                'manager_name' => 'طارق طميزة',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'خدمة مياه أكثر انتظامًا واستجابة لاحتياجات المواطنين.',
                'mission' => 'متابعة التزويد بالمياه ومعالجة الملاحظات وتنسيق أعمال الصيانة بكفاءة.',
                'responsibilities' => "متابعة برامج وتوزيع التزويد بالمياه\nاستقبال ومتابعة الشكاوى المتعلقة بالمياه\nرصد الأعطال والاحتياجات المرتبطة بالشبكة\nتنسيق أعمال الصيانة والإصلاح\nمتابعة المرافق والمنشآت المرتبطة بخدمة المياه",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 5,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'الكهرباء',
                'slug' => 'alkhrbaaa',
                'icon' => 'bolt',
                'short_description' => 'متابعة شؤون الإنارة والكهرباء المرتبطة بالمرافق والخدمات البلدية.',
                'description' => 'تتابع دائرة الكهرباء الاحتياجات المرتبطة بالإنارة والمرافق الكهربائية التابعة للبلدية، وتنسق رصد الأعطال وأعمال الصيانة مع الجهات المختصة بما يحافظ على استمرارية الخدمة وسلامة المرافق.',
                'manager_name' => 'بلال الحتاوي',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'مرافق بلدية مضاءة وآمنة وخدمات كهربائية تتم متابعتها باستجابة فعالة.',
                'mission' => 'رصد احتياجات الإنارة والكهرباء وتنسيق الصيانة بما يخدم المرافق العامة.',
                'responsibilities' => "متابعة أعطال الإنارة في المرافق العامة\nرصد الاحتياجات الكهربائية للمباني والمرافق البلدية\nتنسيق أعمال الصيانة مع الجهات المختصة\nمتابعة إجراءات السلامة في الأعمال الكهربائية\nتوثيق الملاحظات والاحتياجات الفنية المتعلقة بالكهرباء",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 6,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'الصحة',
                'slug' => 'alsh',
                'icon' => 'heart-pulse',
                'short_description' => 'متابعة الجوانب الصحية والبيئية ذات الصلة بالخدمات البلدية.',
                'description' => 'تتابع دائرة الصحة الملاحظات والاحتياجات الصحية المرتبطة بالعمل البلدي، وتنسق مع الجهات المختصة في الموضوعات الصحية والبيئية التي تؤثر في سلامة المجتمع وجودة المرافق العامة.',
                'manager_name' => 'أيمن طميزة',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'بيئة بلدية أكثر صحة وسلامة واستجابة للاحتياجات المجتمعية.',
                'mission' => 'متابعة القضايا الصحية ذات الصلة بالبلدية وتعزيز التنسيق الوقائي مع الجهات المعنية.',
                'responsibilities' => "متابعة الملاحظات الصحية المرتبطة بالمرافق العامة\nرصد الاحتياجات الصحية والبيئية ضمن نطاق العمل البلدي\nالتنسيق مع الجهات المختصة في الموضوعات الصحية\nالمساهمة في نشر التوعية الصحية المرتبطة بالخدمات البلدية\nمتابعة الملاحظات التي قد تؤثر في سلامة المجتمع",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 7,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'الموارد البشرية',
                'slug' => 'almoard-albshry',
                'icon' => 'users',
                'short_description' => 'تنظيم شؤون الموظفين ودعم تطوير الموارد البشرية في البلدية.',
                'description' => 'تتولى دائرة الموارد البشرية تنظيم الملفات والشؤون الإدارية المتعلقة بموظفي البلدية، ودعم إجراءات المتابعة والتطوير، والتنسيق بشأن الاحتياجات البشرية بما يعزز كفاءة العمل المؤسسي.',
                'manager_name' => 'نفين سليمية',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'موارد بشرية كفؤة وبيئة عمل داعمة لخدمة المجتمع.',
                'mission' => 'تنظيم شؤون الموظفين ودعم تطوير قدراتهم بما يخدم أهداف البلدية.',
                'responsibilities' => "تنظيم ومتابعة ملفات الموظفين\nمتابعة الحضور والإجازات والشؤون الوظيفية\nرصد الاحتياجات البشرية للدوائر\nالمساهمة في تنظيم برامج التطوير والتدريب\nإعداد البيانات والتقارير المتعلقة بالموارد البشرية",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 8,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'العلاقات العامة',
                'slug' => 'public-relations',
                'icon' => 'megaphone',
                'short_description' => 'إدارة التواصل المؤسسي ونقل أخبار البلدية وملاحظات المجتمع.',
                'description' => 'تتولى دائرة العلاقات العامة تنظيم التواصل بين البلدية والمواطنين ووسائل الإعلام، وإيصال المعلومات الرسمية عن الأعمال والخدمات، ودعم بناء علاقة واضحة وفعالة مع المجتمع المحلي.',
                'manager_name' => 'عبد الرحمن طميزة',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'تواصل بلدي موثوق ومفتوح يعزز ثقة المجتمع المحلي.',
                'mission' => 'نشر المعلومات البلدية بوضوح، والاستماع إلى المجتمع، ودعم التواصل المؤسسي.',
                'responsibilities' => "إعداد ونشر الأخبار والمعلومات البلدية المعتمدة\nتنظيم التواصل مع المواطنين ووسائل الإعلام\nمتابعة الملاحظات العامة وتحويلها للدوائر المختصة\nدعم تنظيم الفعاليات والأنشطة الرسمية\nالمساهمة في توحيد الرسائل والمعلومات المنشورة",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 9,
                'is_public' => true,
                'is_featured' => false,
            ],
            [
                'name' => 'تكنولوجيا المعلومات',
                'slug' => 'information-technology',
                'icon' => 'monitor',
                'short_description' => 'دعم الأنظمة الرقمية والبنية التقنية والخدمات الإلكترونية للبلدية.',
                'description' => 'تدعم دائرة تكنولوجيا المعلومات تشغيل الأنظمة والأدوات الرقمية في البلدية، وتتابع احتياجات المستخدمين التقنية، وتساهم في استقرار الخدمات الإلكترونية وحماية البيانات ضمن الصلاحيات والإجراءات المعتمدة.',
                'manager_name' => 'شادي البطران',
                'manager_position' => 'مدير الدائرة',
                'phone' => null,
                'extension' => null,
                'mobile' => null,
                'email' => null,
                'office_location' => $officeLocation,
                'working_hours' => $workingHours,
                'vision' => 'بلدية رقمية موثوقة تستخدم التقنية لتحسين الخدمة والعمل المؤسسي.',
                'mission' => 'توفير الدعم التقني ومتابعة الأنظمة الرقمية بما يرفع كفاءة الخدمات البلدية.',
                'responsibilities' => "متابعة تشغيل الأنظمة والتطبيقات البلدية\nتقديم الدعم الفني لمستخدمي الأنظمة\nرصد الأعطال التقنية وتنسيق معالجتها\nالمساهمة في حماية البيانات والنسخ الاحتياطي وفق الإجراءات المعتمدة\nدعم تطوير وتحسين الخدمات الإلكترونية",
                'cover_image_path' => null,
                'status' => 'active',
                'display_order' => 10,
                'is_public' => true,
                'is_featured' => false,
            ],
        ];

        foreach ($departments as $department) {
            Department::updateOrCreate(
                ['slug' => $department['slug']],
                [
                    ...$department,
                    'created_by' => $userId,
                    'updated_by' => $userId,
                ],
            );
        }
    }
}
