<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Authentication\Models\User;
use App\Domains\Department\Models\Department;
use Illuminate\Database\Seeder;

final class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        $adminId = User::first()?->id;

        $departments = [
            [
                'name' => 'قسم الهندسة وال建築',
                'short_description' => 'قسم الهندسة وال建築 مسؤول عن إصدار رخص البناء والإشراف على المشاريع العمرانية.',
                'description' => 'قسم الهندسة وال건축 هو الجهة المعنية بإصدار رخص البناء والمتابعة والإشراف على المشاريع العمرانية في نطاق بلدية إذنا. يشمل القسم مهندسين معماريين ومدنيين مؤهلين.',
                'icon' => 'building-2',
                'manager_name' => 'م. أحمد عودة',
                'manager_position' => 'مدير قسم الهندسة',
                'phone' => '022-100001',
                'mobile' => '0599100001',
                'email' => 'engineering@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الثاني',
                'working_hours' => 'الإحدب - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'تحقيق بناء آمن وموافق للمعايير الهندسية',
                'mission' => 'إشراف على المشاريع العمرانية وفق أعلى المعايير المهنية',
                'status' => 'active',
                'display_order' => 1,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم الشؤون الإدارية والمالية',
                'short_description' => 'قسم الشؤون الإدارية والمالية مسؤول عن إدارة الموارد البشرية والميزانية.',
                'description' => 'قسم الشؤون الإدارية والمالية هو الجهة المعنية بإدارة شؤون الموظفين والميزانية والمشتريات في بلدية إذنا.',
                'icon' => 'wallet',
                'manager_name' => 'محمد حسونة',
                'manager_position' => 'مدير قسم الشؤون الإدارية',
                'phone' => '022-100002',
                'mobile' => '0599100002',
                'email' => 'admin@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الأول',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'إدارة فعالة للموارد البشرية والمالية',
                'mission' => 'تنظيم الشؤون الإدارية والمالية وفق أفضل الممارسات',
                'status' => 'active',
                'display_order' => 2,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم الخدمات البلدية',
                'short_description' => 'قسم الخدمات البلدية مسؤول عن تقديم الخدمات المختلفة للمواطنين.',
                'description' => 'قسم الخدمات البلدية هو الجهة المعنية بتقديم الخدمات البلدية المتنوعة للمواطنين包括 التراخيص والشهادات والخدمات الاجتماعية.',
                'icon' => 'headset',
                'manager_name' => 'فاطمة عودة',
                'manager_position' => 'مديرة قسم الخدمات',
                'phone' => '022-100003',
                'mobile' => '0599100003',
                'email' => 'services@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الأرضي',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'تقديم خدمات بلدية سريعة وفعالة',
                'mission' => 'خدمة المواطن بأفضل جودة وأقصر وقت ممكن',
                'status' => 'active',
                'display_order' => 3,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم التخطيط والتطوير',
                'short_description' => 'قسم التخطيط والتطوير مسؤول عن التخطيط العمراني وتطوير البنية التحتية.',
                'description' => 'قسم التخطيط والتطوير هو الجهة المعنية بالتخطيط العمراني وتطوير البنية التحتية في بلدية إذنا.',
                'icon' => 'map',
                'manager_name' => 'عبدالله عودة',
                'manager_position' => 'مدير قسم التخطيط',
                'phone' => '022-100004',
                'mobile' => '0599100004',
                'email' => 'planning@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الثالث',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'تخطيط عمراني متكامل يخدم مصلحة المواطن',
                'mission' => 'تطوير البنية التحتية وتحسين جودة الحياة',
                'status' => 'active',
                'display_order' => 4,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم البيئة والنظافة',
                'short_description' => 'قسم البيئة والنظافة مسؤول عن حماية البيئة وجمع النفايات.',
                'description' => 'قسم البيئة والنظافة هو الجهة المعنية بحماية البيئة وجمع النفايات وتحسين المظهر العام لمدينة إذنا.',
                'icon' => 'leaf',
                'manager_name' => 'نور عودة',
                'manager_position' => 'مديرة قسم البيئة',
                'phone' => '022-100005',
                'mobile' => '0599100005',
                'email' => 'environment@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الأرضي',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'بيئة نظيفة وخضراء لمدينة إذنا',
                'mission' => 'حماية البيئة وتحسين المظهر العام للمدينة',
                'status' => 'active',
                'display_order' => 5,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم الشؤون القانونية',
                'short_description' => 'قسم الشؤون القانونية مسؤول عن تقديم الاستشارات القانونية والتوثيق.',
                'description' => 'قسم الشؤون القانونية هو الجهة المعنية بتقديم الاستشارات القانونية والتوثيق والخدمات القانونية المختلفة.',
                'icon' => 'shield',
                'manager_name' => 'خالد عودة',
                'manager_position' => 'مدير قسم الشؤون القانونية',
                'phone' => '022-100006',
                'mobile' => '0599100006',
                'email' => 'legal@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الثاني',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'تحقيق العدالة وحماية حقوق المواطن',
                'mission' => 'تقديم الخدمات القانونية بكفاءة وشفافية',
                'status' => 'active',
                'display_order' => 6,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم العلاقات العامة والإعلام',
                'short_description' => 'قسم العلاقات العامة والإعلام مسؤول عن التواصل مع المواطن والإعلام.',
                'description' => 'قسم العلاقات العامة والإعلام هو الجهة المعنية بالتواصل مع المواطن والإعلام وإدارة وسائل التواصل الاجتماعي.',
                'icon' => 'megaphone',
                'manager_name' => 'سارة عودة',
                'manager_position' => 'مديرة قسم العلاقات العامة',
                'phone' => '022-100007',
                'mobile' => '0599100007',
                'email' => 'pr@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الأول',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => 'تواصل فعال مع المواطن والإعلام',
                'mission' => 'إدارة العلاقات العامة وتحسين صورة البلدية',
                'status' => 'active',
                'display_order' => 7,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'قسم التقنية المعلومات',
                'short_description' => 'قسم تقنية المعلومات مسؤول عن إدارة الأنظمة الرقمية والدعم الفني.',
                'description' => 'قسم تقنية المعلومات هو الجهة المعنية بإدارة الأنظمة الرقمية والدعم الفني لجميع أقسام البلدية.',
                'icon' => 'monitor',
                'manager_name' => 'عمر عودة',
                'manager_position' => 'مدير قسم تقنية المعلومات',
                'phone' => '022-100008',
                'mobile' => '0599100008',
                'email' => 'it@idhna.ps',
                'office_location' => 'مبنى البلدية - الطابق الثالث',
                'working_hours' => 'الأحد - الخميس: 8:00 ص - 4:00 م',
                'vision' => '	transformations رقمية متكاملة للبلدية',
                'mission' => 'توفير الحلول التقنية لتحسين الخدمات البلدية',
                'status' => 'active',
                'display_order' => 8,
                'is_public' => true,
                'is_featured' => true,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
        ];

        foreach ($departments as $dept) {
            Department::updateOrCreate(
                ['name' => $dept['name']],
                $dept
            );
        }
    }
}
