<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Domains\Authentication\Models\User;
use App\Domains\ElectronicServices\Models\ElectronicService;
use App\Domains\ElectronicServices\Models\ServiceCategory;
use Illuminate\Database\Seeder;

final class ElectronicServicesSeeder extends Seeder
{
    private const PORTAL_URL = 'https://i.palexpand.ps/portal';

    public function run(): void
    {
        $adminId = User::where('email', 'admin@idhna.ps')->first()?->id;

        $categories = [
            [
                'name' => 'رخص البناء',
                'description' => 'خدمات رخص البناء والتشطيبات العمرانية',
                'icon' => 'building-2',
                'services' => [
                    [
                        'name' => 'طلب رخصة بناء جديد',
                        'summary' => 'التقدم للحصول على رخصة بناء جديدة لمشروع عمراني',
                        'description' => 'خدمة إلكترونية تتيح للمواطنين التقدم للحصول على رخصة بناء جديدة لمشروع عمراني جديد. تشمل الخدمة استلام طلب المواطن، مراجعة المخططات الهندسية، وإصدار الرخصة وفق الأنظمة واللوائح المعمارية المعمول بها.',
                        'eligibility' => 'مالك الأرض أو ممثله القانوني具备 صلاحية التقدم للطلب',
                        'requirements' => ['صورة هوية م sclerosis', 'رخصة ملكية أو مستخرج قياسي', 'المخططات الهندسية المعتمدة', 'عقد التأمين ضد المخاطر'],
                        'documents' => ['هوية م sclerosis', 'رخصة ملكية', 'مخططات هندسية', 'عقد تأمين'],
                        'steps' => ['تقديم الطلب إلكترونياً', 'مراجعة الملف من قبل القسم', 'اعتماد المخططات', 'إصدار الرخصة'],
                        'fees' => ['رسوم الإصدار: 100₪', 'رسوم المراجعة: 50₪'],
                        'processing_time' => '5-7 أيام عمل',
                        'department_id' => 1,
                    ],
                    [
                        'name' => 'طلب تجديد رخصة بناء',
                        'summary' => 'تجديد رخصة بناء منتهية الصلاحية',
                        'description' => 'خدمة تجديد رخصة بناء منتهية الصلاحية. يمكن للمواطنين تجديد رخصتهم قبل انتهاء صلاحيتها بـ 30 يوماً.',
                        'eligibility' => 'صاحب رخصة بناء سارية الصلاحية',
                        'requirements' => ['صورة هوية', 'رخصة البناء الأصلية', 'تقرير التقدم في العمل'],
                        'documents' => ['هوية م sclerosis', 'رخصة بناء', 'تقرير عمل'],
                        'steps' => ['تقديم طلب التجديد', 'مراجعة التقدم في العمل', 'إصدار تجديد الرخصة'],
                        'fees' => ['رسوم التجديد: 75₪'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 1,
                    ],
                    [
                        'name' => 'طلب تعديل رخصة بناء',
                        'summary' => 'طلب تعديل على رخصة بناء صادرة',
                        'description' => 'خدمة تعديل رخصة بناء صادرة لإجراء تغييرات على المخططات المعتمدة.',
                        'eligibility' => 'صاحب رخصة بناء صادرة',
                        'requirements' => ['هوية م sclerosis', 'رخصة بناء', 'المخططات المعدلة', 'تبرير التعديل'],
                        'documents' => ['هوية م sclerosis', 'رخصة بناء', 'مخططات معدلة'],
                        'steps' => ['تقديم طلب التعديل', 'مراجعة التعديلات', 'اعتماد التعديلات', 'إصدار رخصة معدّلة'],
                        'fees' => ['رسوم التعديل: 50₪'],
                        'processing_time' => '5-10 أيام عمل',
                        'department_id' => 1,
                    ],
                    [
                        'name' => 'طلب شهادة إتمام بناء',
                        'summary' => 'الحصول على شهادة إتمام البناء',
                        'description' => 'خدمة إصدار شهادة إتمام بناء بعد الانتهاء من جميع الأعمال البنائية وفق الرخصة الصادرة.',
                        'eligibility' => 'صاحب رخصة بناء مكتملة',
                        'requirements' => ['هوية م sclerosis', 'رخصة بناء', 'تقرير ختامي من المهندس المشرف'],
                        'documents' => ['هوية م sclerosis', 'رخصة بناء', 'تقرير ختامي'],
                        'steps' => ['تقديم الطلب', 'الفحص الميداني', 'إصدار الشهادة'],
                        'fees' => ['رسوم الإصدار: 150₪'],
                        'processing_time' => '7-10 أيام عمل',
                        'department_id' => 1,
                    ],
                    [
                        'name' => 'طلب هدم مبنى',
                        'summary' => 'الحصول على تصريح هدم مبنى',
                        'description' => 'خدمة الحصول على تصريح لهدم مبنى أو جزء منه وفق الأنظمة المعمارية.',
                        'eligibility' => 'مالك المبنى أو ممثله القانوني',
                        'requirements' => ['هوية م sclerosis', 'رخصة ملكية', 'تقرير هندسي عن حالة المبنى', 'خطاب موافقة الجيران'],
                        'documents' => ['هوية م sclerosis', 'رخصة ملكية', 'تقرير هندسي', 'خطاب موافقة'],
                        'steps' => ['تقديم الطلب', 'الفحص الفني', 'إصدار التصريح', 'تنفيذ الهدم'],
                        'fees' => ['رسوم التصريح: 200₪'],
                        'processing_time' => '10-15 يوم عمل',
                        'department_id' => 1,
                    ],
                    [
                        'name' => 'طلب ترخيص محل تجاري',
                        'summary' => 'الحصول على ترخيص لمحل تجاري',
                        'description' => 'خدمة إصدار ترخيص لمحل تجاري جديد أو تجديد ترخيص محل موجود.',
                        'eligibility' => 'صاحب محل تجاري أو مستأجره',
                        'requirements' => ['هوية م sclerosis', 'عقد إيجار أو ملكية', 'شهادة صحية', 'شهادة إطفاء'],
                        'documents' => ['هوية م sclerosis', 'عقد إيجار', 'شهادة صحية', 'شهادة إطفاء'],
                        'steps' => ['تقديم الطلب', 'الفحص الميداني', 'إصدار الترخيص'],
                        'fees' => ['رسوم الترخيص: 300₪ سنوياً'],
                        'processing_time' => '5-7 أيام عمل',
                        'department_id' => 2,
                    ],
                ],
            ],
            [
                'name' => 'الشؤون الإدارية',
                'description' => 'خدمات الشؤون الإدارية والمالية',
                'icon' => 'wallet',
                'services' => [
                    [
                        'name' => 'طلب صرف مكافأة نهاية الخدمة',
                        'summary' => 'تقديم طلب صرف مكافأة نهاية خدمة للموظفين',
                        'description' => 'خدمة إلكترونية تتيح للموظفين المتقاعدين التقدم لطلب صرف مكافأة نهاية الخدمة.',
                        'eligibility' => 'موظف متقاعد من خدمة البلدية',
                        'requirements' => ['خطاب تقاعد', 'هوية م sclerosis', 'كشف حساب بنكي'],
                        'documents' => ['خطاب تقاعد', 'هوية م sclerosis', 'كشف حساب'],
                        'steps' => ['تقديم الطلب', 'مراجعة المستحقات', 'اعتماد الميزانية', 'صرف المكافأة'],
                        'fees' => ['مجاني'],
                        'processing_time' => '15-30 يوم عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب إجازة استثنائية',
                        'summary' => 'التقدم لطلب إجازة استثنائية',
                        'description' => 'خدمة تتيح للموظفين التقدم لطلب إجازة استثنائية لأسباب خاصة.',
                        'eligibility' => 'موظف حالي في خدمة البلدية',
                        'requirements' => ['طلب مبرر', 'أثر طبي أو وثيقة داعمة'],
                        'documents' => ['طلب إجازة', 'أثر طبي'],
                        'steps' => ['تقديم الطلب', 'مراجعة المدير المباشر', 'اعتماد الموارد البشرية'],
                        'fees' => ['مجاني'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب شهادة عمل',
                        'summary' => 'الحصول على شهادة عمل من البلدية',
                        'description' => 'خدمة إصدار شهادة عمل للموظفين الحاليين أو السابقين في البلدية.',
                        'eligibility' => 'موظف حالي أو سابق في البلدية',
                        'requirements' => ['هوية م sclerosis', 'طلب مكتوب'],
                        'documents' => ['هوية م sclerosis', 'طلب شهادة عمل'],
                        'steps' => ['تقديم الطلب', 'إعداد الشهادة', 'تسليم الشهادة'],
                        'fees' => ['مجاني'],
                        'processing_time' => '1-2 أيام عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب صرف راتب',
                        'summary' => 'طلب صرف راتب شهري',
                        'description' => 'خدمة للموظفين لطلب صرف رواتبهم الشهرية عبر البوابة الإلكترونية.',
                        'eligibility' => 'موظف حالي في البلدية',
                        'requirements' => ['رقم الموظف', 'كشف حساب بنكي'],
                        'documents' => ['كشف حساب بنكي'],
                        'steps' => ['تسجيل الدخول', 'تأكيد بيانات الراتب', 'اعتماد المدير', 'صرف الراتب'],
                        'fees' => ['مجاني'],
                        'processing_time' => '1-3 أيام عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب تدريب مهني',
                        'summary' => 'التقدم لبرنامج تدريب مهني',
                        'description' => 'خدمة تتيح للموظفين التقدم للمشاركة في برامج التدريب المهني والتطوير الوظيفي.',
                        'eligibility' => 'موظف حالي في البلدية بخبرة لا تقل عن سنة',
                        'requirements' => ['طلب مبرر', 'موافقة المدير المباشر'],
                        'documents' => ['طلب تدريب', 'موافقة المدير'],
                        'steps' => ['تقديم الطلب', 'مراجعة الأهلية', 'اعتماد الموارد البشرية', 'التسجيل في البرنامج'],
                        'fees' => ['مجاني'],
                        'processing_time' => '5-7 أيام عمل',
                        'department_id' => 3,
                    ],
                ],
            ],
            [
                'name' => 'الشؤون القانونية',
                'description' => 'خدمات الشؤون القانونية والاستشارات',
                'icon' => 'shield',
                'services' => [
                    [
                        'name' => 'طلب استشارة قانونية',
                        'summary' => 'التقدم لطلب استشارة قانونية من البلدية',
                        'description' => 'خدمة تتيح للمواطنين طلب استشارة قانونية من قسم الشؤون القانونية في البلدية.',
                        'eligibility' => 'مواطن مسجل في بلدية إذنا',
                        'requirements' => ['هوية م sclerosis', 'موضوع الاستشارة'],
                        'documents' => ['هوية م sclerosis', 'وثيقة الاستشارة'],
                        'steps' => ['تقديم الطلب', 'تحديد موعد الاستشارة', 'تقديم الاستشارة'],
                        'fees' => ['مجاني'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 7,
                    ],
                    [
                        'name' => 'طلب توثيق عقد',
                        'summary' => 'توثيق عقد بين أطراف',
                        'description' => 'خدمة توثيق العقود الرسمية بين الأطراف المختلفة عبر البلدية.',
                        'eligibility' => 'أطراف العقد',
                        'requirements' => ['هويات الأطراف', 'العقد المكتوب', 'شهود'],
                        'documents' => ['هويات الأطراف', 'العقد'],
                        'steps' => ['تقديم العقد', 'مراجعة الشروط', 'توقيع الأطراف', 'توثيق العقد'],
                        'fees' => ['رسوم التوثيق: 100₪'],
                        'processing_time' => '1-3 أيام عمل',
                        'department_id' => 7,
                    ],
                    [
                        'name' => 'طلب إصدار شهادة إخلال طرف',
                        'summary' => 'الحصول على شهادة إخلال طرف',
                        'description' => 'خدمة إصدار شهادة إخلال طرف للعمل في الجهات الرسمية.',
                        'eligibility' => 'مواطن مسجل في بلدية إذنا',
                        'requirements' => ['هوية م sclerosis', 'لا يوجد التزامات مالية'],
                        'documents' => ['هوية م sclerosis'],
                        'steps' => ['تقديم الطلب', 'التحقق من التزامات', 'إصدار الشهادة'],
                        'fees' => ['رسوم الإصدار: 25₪'],
                        'processing_time' => '1-2 أيام عمل',
                        'department_id' => 7,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات الصحية',
                'description' => 'خدمات صحية وبيئية للمواطنين',
                'icon' => 'heart-pulse',
                'services' => [
                    [
                        'name' => 'طلب ترخيص مطبخ منزلي',
                        'summary' => 'الحصول على ترخيص لمطبخ منزلي',
                        'description' => 'خدمة إصدار ترخيص لمطبخ منزلي لبيع الطعام.',
                        'eligibility' => 'مواطن يريد فتح مطبخ منزلي',
                        'requirements' => ['هوية م sclerosis', 'شهادة صحية', 'صور للمطبخ', 'خطة التعقيم'],
                        'documents' => ['هوية م sclerosis', 'شهادة صحية', 'صور المطبخ'],
                        'steps' => ['تقديم الطلب', 'الفحص الصحي', 'إصدار الترخيص'],
                        'fees' => ['رسوم الترخيص: 200₪ سنوياً'],
                        'processing_time' => '5-7 أيام عمل',
                        'department_id' => 2,
                    ],
                    [
                        'name' => 'طلب فحص صحي لمحل',
                        'summary' => 'طلب فحص صحي لمحل تجاري',
                        'description' => 'خدمة طلب فحص صحي لمحل تجاري قبل إصدار أو تجديد الترخيص.',
                        'eligibility' => 'صاحب محل تجاري',
                        'requirements' => ['هوية م sclerosis', 'ترخيص المحل'],
                        'documents' => ['هوية م sclerosis', 'ترخيص'],
                        'steps' => ['تقديم الطلب', 'الفحص الميداني', 'إصدار التقرير'],
                        'fees' => ['رسوم الفحص: 50₪'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 2,
                    ],
                    [
                        'name' => 'طلب مكافحة حشرات',
                        'summary' => 'طلب خدمة مكافحة حشرات',
                        'description' => 'خدمة مكافحة الحشرات والقوارض للأماكن العامة والخاصة.',
                        'eligibility' => 'مواطن في منطقة الخدمة',
                        'requirements' => ['عنوان المكان', 'وصف المشكلة'],
                        'documents' => [],
                        'steps' => ['تقديم الطلب', 'تحديد موعد', 'تنفيذ المكافحة'],
                        'fees' => ['مجاني للأماكن العامة', '50₪ للأماكن الخاصة'],
                        'processing_time' => '3-7 أيام عمل',
                        'department_id' => 2,
                    ],
                    [
                        'name' => 'طلب شهادة صحية',
                        'summary' => 'الحصول على شهادة صحية',
                        'description' => 'خدمة إصدار شهادة صحية للمواطنين.',
                        'eligibility' => 'مواطن مسجل في بلدية إذنا',
                        'requirements' => ['هوية م sclerosis', 'فحص طبي'],
                        'documents' => ['هوية م sclerosis'],
                        'steps' => ['تقديم الطلب', 'الفحص الطبي', 'إصدار الشهادة'],
                        'fees' => ['رسوم الفحص: 30₪'],
                        'processing_time' => '1-3 أيام عمل',
                        'department_id' => 2,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات المالية',
                'description' => 'خدمات مالية وضرائب بلدية',
                'icon' => 'circle-dollar-sign',
                'services' => [
                    [
                        'name' => 'طلب صرف شيك بلدي',
                        'summary' => 'صرف شيك من خزينة البلدية',
                        'description' => 'خدمة صرف الشيكات الصادرة من خزينة البلدية للمستحقين.',
                        'eligibility' => 'مستحق مالي من البلدية',
                        'requirements' => ['هوية م sclerosis', 'رقم المستحقية', 'كشف حساب بنكي'],
                        'documents' => ['هوية م sclerosis', 'كشف حساب'],
                        'steps' => ['تقديم الطلب', 'التحقق من المستحقية', 'اعتماد المحاسب', 'صرف الشيك'],
                        'fees' => ['مجاني'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب دفع رسوم بلدية',
                        'summary' => 'دفع الرسوم البلدية المستحقة',
                        'description' => 'خدمة دفع الرسوم البلدية المختلفة عبر البوابة الإلكترونية.',
                        'eligibility' => ' المواطن لديه التزامات مالية بلدية',
                        'requirements' => ['رقم الحساب', 'وسيلة دفع إلكترونية'],
                        'documents' => [],
                        'steps' => ['تسجيل الدخول', 'عرض المستحقات', 'اختيار طريقة الدفع', 'تأكيد الدفع'],
                        'fees' => ['مجاني'],
                        'processing_time' => 'فوري',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب استعلام عن رصيد',
                        'summary' => 'الاستعلام عن الرصيد المالي لدى البلدية',
                        'description' => 'خدمة الاستعلام عن الرصيد المالي للمواطن لدى البلدية.',
                        'eligibility' => 'مواطن مسجل في بلدية إذنا',
                        'requirements' => ['هوية م sclerosis'],
                        'documents' => ['هوية م sclerosis'],
                        'steps' => ['تسجيل الدخول', 'عرض الرصيد'],
                        'fees' => ['مجاني'],
                        'processing_time' => 'فوري',
                        'department_id' => 3,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات الاجتماعية',
                'description' => 'خدمات اجتماعية ودعم مجتمعي',
                'icon' => 'users',
                'services' => [
                    [
                        'name' => 'طلب مساعدة اجتماعية',
                        'summary' => 'التقدم لطلب مساعدة اجتماعية',
                        'description' => 'خدمة تقديم طلب مساعدة اجتماعية للمواطنين المحتاجين.',
                        'eligibility' => 'مواطن في وضع صعب مادياً',
                        'requirements' => ['هوية م sclerosis', 'إثبات الدخل', 'تقرير اجتماعي'],
                        'documents' => ['هوية م sclerosis', 'إثبات دخل', 'تقرير اجتماعي'],
                        'steps' => ['تقديم الطلب', 'التقييم الاجتماعي', 'اعتماد اللجنة', 'صرف المساعدة'],
                        'fees' => ['مجاني'],
                        'processing_time' => '15-30 يوم عمل',
                        'department_id' => 3,
                    ],
                    [
                        'name' => 'طلب دعم تعليمي',
                        'summary' => 'التقدم لطلب دعم تعليمي',
                        'description' => 'خدمة تقديم دعم تعليمي للطلاب المحتاجين.',
                        'eligibility' => 'طالب في مرحلة تعليمية',
                        'requirements' => ['هوية الطالب', 'شهادة قيد', 'إثبات الدخل'],
                        'documents' => ['هوية الطالب', 'شهادة قيد'],
                        'steps' => ['تقديم الطلب', 'التقييم', 'اعتماد اللجنة', 'صرف الدعم'],
                        'fees' => ['مجاني'],
                        'processing_time' => '10-20 يوم عمل',
                        'department_id' => 3,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات البيئية',
                'description' => 'خدمات بيئية ونظافة',
                'icon' => 'leaf',
                'services' => [
                    [
                        'name' => 'طلب نقل نفايات',
                        'summary' => 'طلب خدمة نقل نفايات',
                        'description' => 'خدمة طلب نقل النفايات من الأماكن العامة أو الخاصة.',
                        'eligibility' => 'مواطن في منطقة الخدمة',
                        'requirements' => ['عنوان المكان', 'نوع النفايات'],
                        'documents' => [],
                        'steps' => ['تقديم الطلب', 'تحديد الموعد', 'تنفيذ النقل'],
                        'fees' => ['مجاني للنفايات المنزلية', 'رسوم خاصة للنفايات الصناعية'],
                        'processing_time' => '1-3 أيام عمل',
                        'department_id' => 5,
                    ],
                    [
                        'name' => 'طلب زراعة أشجار',
                        'summary' => 'طلب زراعة أشجار في الأماكن العامة',
                        'description' => 'خدمة طلب زراعة أشجار في الأماكن العامة والحدائق.',
                        'eligibility' => 'مواطن أو جمعية محلية',
                        'requirements' => ['عنوان المكان', 'نوع الشجرة المطلوبة'],
                        'documents' => [],
                        'steps' => ['تقديم الطلب', 'مراجعة feasibility', 'التنفيذ'],
                        'fees' => ['مجاني'],
                        'processing_time' => '7-14 يوم عمل',
                        'department_id' => 5,
                    ],
                    [
                        'name' => 'طلب تصريح حفر',
                        'summary' => 'الحصول على تصريح حفر',
                        'description' => 'خدمة الحصول على تصريح لحفر في الأماكن العامة.',
                        'eligibility' => 'مواطن أو شركة مقاولات',
                        'requirements' => ['هوية م sclerosis', 'خطاب الجهة المعنية', 'خطة العمل'],
                        'documents' => ['هوية م sclerosis', 'خطاب', 'خطة عمل'],
                        'steps' => ['تقديم الطلب', 'مراجعة الخطة', 'إصدار التصريح'],
                        'fees' => ['رسوم التصريح: 150₪'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 5,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات التخطيطية',
                'description' => 'خدمات تخطيط وتطوير عمراني',
                'icon' => 'map',
                'services' => [
                    [
                        'name' => 'طلب مخطط موقع',
                        'summary' => 'الحصول على مخطط موقع',
                        'description' => 'خدمة إصدار مخطط موقع لقطعة أرض معينة.',
                        'eligibility' => 'مالك الأرض أو ممثله القانوني',
                        'requirements' => ['هوية م sclerosis', 'رخصة ملكية', 'صورة للقطعة'],
                        'documents' => ['هوية م sclerosis', 'رخصة ملكية'],
                        'steps' => ['تقديم الطلب', 'إعداد المخطط', 'تسليم المخطط'],
                        'fees' => ['رسوم الإعداد: 100₪'],
                        'processing_time' => '5-10 أيام عمل',
                        'department_id' => 6,
                    ],
                    [
                        'name' => 'طلب شهادة مطابقة',
                        'summary' => 'الحصول على شهادة مطابقة للمخطط',
                        'description' => 'خدمة إصدار شهادة مطابقة للمخطط المعتمدة.',
                        'eligibility' => 'صاحب مخطط معتمدة',
                        'requirements' => ['هوية م sclerosis', 'المخطط المعتمدة'],
                        'documents' => ['هوية م sclerosis', 'مخطط'],
                        'steps' => ['تقديم الطلب', 'المقارنة', 'إصدار الشهادة'],
                        'fees' => ['رسوم الإصدار: 75₪'],
                        'processing_time' => '3-5 أيام عمل',
                        'department_id' => 6,
                    ],
                ],
            ],
            [
                'name' => 'الخدمات الإلكترونية',
                'description' => 'خدمات رقمية وإلكترونية متنوعة',
                'icon' => 'laptop',
                'services' => [
                    [
                        'name' => 'طلب خدمة رقمية',
                        'summary' => 'التقدم لخدمة رقمية متنوعة',
                        'description' => 'خدمة إلكترونية متنوعة تشمل طلبات رقمية متعددة.',
                        'eligibility' => 'مواطن مسجل في بلدية إذنا',
                        'requirements' => ['حساب مستخدم مسجل'],
                        'documents' => [],
                        'steps' => ['تسجيل الدخول', 'اختيار الخدمة', 'إكمال البيانات', 'تقديم الطلب'],
                        'fees' => ['حسب نوع الخدمة'],
                        'processing_time' => 'حسب نوع الخدمة',
                        'department_id' => 8,
                    ],
                    [
                        'name' => 'طلب دعم فني',
                        'summary' => 'الحصول على دعم فني للخدمات الإلكترونية',
                        'description' => 'خدمة دعم فني للمواطنين الذين يواجهون مشاكل في استخدام الخدمات الإلكترونية.',
                        'eligibility' => 'مواطن يستخدم الخدمات الإلكترونية',
                        'requirements' => ['وصف المشكلة'],
                        'documents' => [],
                        'steps' => ['تقديم الطلب', 'التواصل مع الدعم', 'حل المشكلة'],
                        'fees' => ['مجاني'],
                        'processing_time' => '1-2 أيام عمل',
                        'department_id' => 8,
                    ],
                ],
            ],
        ];

        $sortOrder = 0;
        foreach ($categories as $catData) {
            $category = ServiceCategory::firstOrCreate(
                ['name' => $catData['name']],
                [
                    'description' => $catData['description'],
                    'icon' => $catData['icon'],
                    'status' => 'active',
                    'is_public' => true,
                    'sort_order' => $sortOrder,
                    'created_by' => $adminId,
                    'updated_by' => $adminId,
                ]
            );

            $sortOrder++;

            foreach ($catData['services'] as $index => $serviceData) {
                ElectronicService::firstOrCreate(
                    [
                        'service_category_id' => $category->id,
                        'name' => $serviceData['name'],
                    ],
                    [
                        'department_id' => $serviceData['department_id'] ?? null,
                        'summary' => $serviceData['summary'] ?? null,
                        'description' => $serviceData['description'] ?? null,
                        'eligibility' => $serviceData['eligibility'] ?? null,
                        'requirements' => $serviceData['requirements'] ?? null,
                        'documents' => $serviceData['documents'] ?? null,
                        'steps' => $serviceData['steps'] ?? null,
                        'fees' => $serviceData['fees'] ?? null,
                        'processing_time' => $serviceData['processing_time'] ?? null,
                        'portal_url' => self::PORTAL_URL,
                        'requires_login' => true,
                        'status' => 'active',
                        'is_public' => true,
                        'is_featured' => $index < 2,
                        'sort_order' => $index,
                        'views_count' => rand(50, 500),
                        'portal_clicks_count' => rand(10, 200),
                        'created_by' => $adminId,
                        'updated_by' => $adminId,
                        'published_at' => now(),
                    ]
                );
            }
        }
    }
}
